### PR TITLE
fix(transactional): use proxy on descriptor.value

### LINKED ISSUE #149: @Transactional decorator breaking swagger documentation
Hi, I'm having a problem with the @Transactional decorator. When I add it to a controller method, the corresponding post on the swagger documentation loses its corresponding openapi.ApiResponse. I've looked at the compiled JS code and both decorators are being added correctly, so I'm not entirely sure where the problem could be coming from, but I'm not well versed in NestJS decorators. Do you have any idea what might be causing it?

For example:
These two endpoints:
```
  @Post()
  @UseGuards(AuthGuard)
  async create(@Body() dto: CreateNaturalPersonWithPersonWithLocationDto): Promise<GetNaturalPersonWithPersonWithLocationDto> {
    const naturalPerson = await this.personNaturalCreatorService.createWithPersonWithLocation({ dto });
    return this.personNaturalGetterService.getById({ id: naturalPerson.id });
  }

  @Post('/d')
  async createx(@Body() dto: CreateNaturalPersonWithPersonWithLocationDto): Promise<GetNaturalPersonWithPersonWithLocationDto> {
    const naturalPerson = await this.personNaturalCreatorService.createWithPersonWithLocation({ dto });
    return this.personNaturalGetterService.getById({ id: naturalPerson.id });
  }

  @Post('/s')
  @Transactional()
  async created(@Body() dto: CreateNaturalPersonWithPersonWithLocationDto): Promise<GetNaturalPersonWithPersonWithLocationDto> {
    const naturalPerson = await this.personNaturalCreatorService.createWithPersonWithLocation({ dto });
    return this.personNaturalGetterService.getById({ id: naturalPerson.id });
  }
}
```

The first two have the post schema on swagger, while the last doesn't. However, the compiled JS:
```
__decorate([
    (0, common_1.Post)(),
    (0, common_1.UseGuards)(auth_guard_1.AuthGuard),
    openapi.ApiResponse({ status: 201, type: require("./dto/getNaturalPerson.dto").GetNaturalPersonWithPersonWithLocationDto }),
    __param(0, (0, common_1.Body)()),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [createNaturalPerson_dto_1.CreateNaturalPersonWithPersonWithLocationDto]),
    __metadata("design:returntype", Promise)
], PersonNaturalController.prototype, "create", null);
__decorate([
    (0, common_1.Post)('/d'),
    openapi.ApiResponse({ status: 201, type: require("./dto/getNaturalPerson.dto").GetNaturalPersonWithPersonWithLocationDto }),
    __param(0, (0, common_1.Body)()),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [createNaturalPerson_dto_1.CreateNaturalPersonWithPersonWithLocationDto]),
    __metadata("design:returntype", Promise)
], PersonNaturalController.prototype, "createx", null);
__decorate([
    (0, common_1.Post)('/s'),
    (0, transactional_1.Transactional)(),
    openapi.ApiResponse({ status: 201, type: require("./dto/getNaturalPerson.dto").GetNaturalPersonWithPersonWithLocationDto }),
    __param(0, (0, common_1.Body)()),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [createNaturalPerson_dto_1.CreateNaturalPersonWithPersonWithLocationDto]),
    __metadata("design:returntype", Promise)
], PersonNaturalController.prototype, "created", null);
```

Has the correct decorators from what I can see. What could the cause of the problem?

Edit:
On further inspection I found this [issue](https://github.com/nestjs/swagger/issues/217) on the swagger repo. I think this might be what's wrong with @Transactional as it also overwrites the property.

### PR DESCRIPTION
**Pull request by nicobuzeta**
Fixes #149 by using a Proxy object to avoid overiding descriptor.value inside the decorator.

### CODE REVIEW

File: packages/transactional/src/lib/transactional.decorator.ts [hunk 1]
```diff
@@ -113,20 +113,22 @@ export function Transactional(
                 `The @Transactional decorator can be only used on functions, but ${propertyKey.toString()} is not a function.`,
             );
         }
-        descriptor.value = function (...args: any[]) {
-            if (!this[transactionHostProperty]) {
-                throw new Error(
-                    `Failed to inject transaction host into ${target.constructor.name}`,
+        descriptor.value = new Proxy(original, {
+            apply: function (_, outerThis, ...args: any[]) {
```
Comment (Papooch) [inline packages/transactional/src/lib/transactional.decorator.ts:117]:
```suggestion
            apply: function (_, outerThis, args: any[]) {
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/apply), the signature of the apply trap is `apply(target, thisArg, argumentsList)`

I just realized that the tests were only passing, because the `@Transactional` decorator was only ever used on methods with a single argument that was later immediately stringified, which produces the same result:

```node
> (1).toString()
'1'
> ([1]).toString()
'1'
```

But this is wrong behavior and would break existing code.

**Review by Papooch — CHANGES_REQUESTED** [review]
Thanks for the PR. Please fix the issue I mentioned and then I'll go ahead and merge it.

If you feel like it, you could have a go at writing tests for the decorator that it correctly preserves metadata (If not, I'll add them later)

File: packages/transactional/src/lib/transactional.decorator.ts (hunk 1 above)
Comment (nicobuzeta) [reply packages/transactional/src/lib/transactional.decorator.ts:117]: Totally right, completely overlooked it when doing the change.

**Comment by nicobuzeta** [comment]
I investigated a little further, and it's a little puzzling as to why the original method didn't work since it already copies over the necessary metadata. I have to assume that swagger must add some property to the method outside of metadata as that is already being copied over correctly.  This is quite strange as I looked over the ApiResponse code and I could only see metadata being defined.

I've added two tests, one to check that the metadata is being passed over correctly, which passes with the previous code, and one to check that properties are accessible through the proxy.

**Review by Papooch — CHANGES_REQUESTED** [review]
Hey, thanks for the fix and the tests.

However, mixing actual transaction tests with metadata checking tests is not very transparent, so I'd like to ask you to put the decorator tests into a separate file `transactional.decorator.spec.ts` (together with the mock decorators). 

Apart from that, everything looks fine to me.

**Comment by nicobuzeta** [comment]
How do I handle checking if adding metadata breaks the transaction decorator? I added it to the original tests to verify that adding other decorators doesn't break the transactions. Should I add some simple transaction test to the new spec file or just check the metadata and assume adding new decorators doesn't affect @Transactional?

**Comment by Papooch** [comment]
> How do I handle checking if adding metadata breaks the transaction decorator

Personally, I would add a simple transaction test (using the mock adapter) for a method that accepts multiple parameters and asserts that it received them unchanged.

**Review by Papooch — APPROVED** [review]
Thank you, this looks alright to me :)
